### ISSUE TITLE
The title of the app should be "UCSB Courses Search"  not "Demo CRA + Spring App"

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156-w21/proj-ucsb-courses-search#92] opened 2020-12-12 04:47 UTC
# User Story

As a user I can see the name of the app in the title (i.e. the tab in my browser) so that I can easily find this app among my browser tabs.

That is, instead of seeing this:

![image](https://user-images.githubusercontent.com/1119017/101975395-188d4280-3bf1-11eb-9bf8-e2d078c6d04b.png)

I want to see the text "UCSB Courses Search" in place of "Demo CRA + Spring App"

# Acceptance Criteria

- [ ] I should see "UCSB Courses Search"   in place of "Demo CRA + Spring App" in the browser tab.

# Implementation Todos

Front end:

- [ ] In the file `javascript/public/index.html` change the title element to "UCSB Courses Search" 

Testing:

- [ ] Existing Front end tests pass and there is adequate coverage
- [ ] Add a test that loads the app and specifically looks for the title element on the page, checking that it contains "UCSB Courses Search"

**Comment by 96RadhikaJadhav** [comment] 2020-12-12 18:17
@pconrad Can I work on this issue?

**Comment by andrewhlu** [comment] 2021-02-17 08:41
Duplicate of #124

**Closed by andrewhlu** 2021-02-17 08:41 UTC
Labels: W21, good first issue
