### ISSUE TITLE
Change colors of courses in course table based on whether they are open/closed/cancelled.

### ISSUE THREAD

**Issue by mara-downing** [ucsb-cs156-w21/proj-ucsb-courses-search#140] opened 2021-02-22 23:06 UTC
# User Story

As a user I can easily see which courses are open/closed/full in the course table by displaying them in different colors.

# Acceptance Criteria

- [ ] Courses which are full are colored differently from open courses.
- [ ] Courses that are cancelled are also colored differently from open courses, and from full courses.

# Implementation Todos

Note: You could continue the work of PR #74 or start from scratch. If you are continuing, talk to staff about color choices/possible bugs.

Front end:

- [ ] Decide on a good readable color scheme and add a key to explain which color corresponds to which course status.
- [ ] Compute which courses should have each color.
- [ ] Change the color of courses in the basic course search table based on their status as open/full/cancelled.

Back end:
Nothing to do.

Testing:

- [ ] Front end tests pass and there is adequate coverage
- [ ] Back end tests pass and there is adequate coverage

**Comment by andrewhlu** [comment] 2021-02-23 00:14
Duplicate of #62.

**Closed** 2021-02-23 00:14 UTC
Labels: UX Improvements
