### ISSUE TITLE
Add Search by Instructor

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156-w21/proj-ucsb-courses-search#28] opened 2020-11-19 18:49 UTC
As a user, I can enter an instructor, start quarter, and end quarter, and see all the courses that instructor has taught over time.

**Comment by htransteven** [comment] 2021-02-03 01:24
Duplicate of #32, closing issue.

**Comment by htransteven** [comment] 2021-02-03 01:25
Duplicate of #32

**Closed by htransteven** 2021-02-03 01:25 UTC
